# Generated by Django 5.1.6 on 2025-03-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_pictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures',
            new_name='Picture',
        ),
    ]
