# Generated by Django 5.1.6 on 2025-03-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('thumbnail_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
