# Generated by Django 5.1.6 on 2025-03-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='agencies/')),
            ],
        ),
    ]
