# Generated by Django 5.1.6 on 2025-03-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_jingles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
